### ISSUE TITLE
Android 31 is the only version supported

### ISSUE THREAD

**Issue by manuelelucchi** [julienGrd/BigIslandBarcoding#3]
Visual Studio complains about the usage of the library since it seems to not be available for Android SDK < 31

**Comment by StepKie** [comment]
I have the same issue, is SDK 31 really necessary, since MAUI has issues with Android 31 ([example](https://github.com/dotnet/maui/issues/7772)).

Is it possible to get the nuget configured with a lower dependency? Thanks for all your work!

**Comment by Realinspirer** [comment]
Actually it truly only is supported above Android 30. I tested, and WSA (Windows Subsystem for Android™️ 12.1) gave the result, but my physical device (Android 8.1) couldn't give a result. It shows the camera correctly, but it just cannot read the codes.
Do anyone have any other experience? Am I just tripping or what?

**Comment by Realinspirer** [comment]
Wait I tried another QR, and it worked...lmao..what.

**Comment by Realinspirer** [comment]
This probably doesn't work for 1 dimensional barcodes.
[EDIT] (don't wanna comment and expand this thread, as it would feel I am talking to myself.)
One dimensional barcodes can only be read when the orientation is landscape.

**Comment by julienGrd** [comment]
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work
