### ISSUE TITLE
Looks like this can only scan qr code, not barcode

### ISSUE THREAD

**Issue by Ihone8** [julienGrd/BigIslandBarcoding#4]

**Comment by JoseW3b** [comment]
It seems only read barcodes in one direction... without any rotation of camera nor barcode

**Comment by Ihone8** [comment]
> It seems only read barcodes in one direction... without any rotation of camera nor barcode
Can you read bar codes properly? The android emulator I'm currently using doesn't seem to be able to read bar codes

**Comment by Ihone8** [comment]
@JoseW3b  If you can read bar codes properly, can you show me a demo?

**Comment by Ihone8** [comment]
@JoseW3b  Thank you very much. I can scan the bar code normally, but I have to turn my phone sideways to scan it

**Comment by JoseW3b** [comment]
@Ihone8 Yes, that's is.
