### ISSUE TITLE
Options are not correctly set to ZXingBarcodeReader from CameraBarcodeReaderView

### ISSUE THREAD

**Issue by kajzik** [julienGrd/BigIslandBarcoding#6]
Testing via nuget package on my project, reading 1D barcode recognize only 90° tilted. After downloading whole project i discovered that property `ZXingBarcodeReader.Options` is set to its default valu in `ZXingBarcodeReader.Decode` method, `AutoRotate` is false therefore it does not try rotate image. Same for another settings in `BarcodeReaderOptions`.
Can you confirm this behavior?

**Comment by vgb1993** [comment]
I can confirm that I have the same problem. Only if I rtate the phone 90º it will detect 1D barcodes.

Did you solve this in some way?

**Comment by kajzik** [comment]
Don't use this project instead use [https://github.com/redth/ZXing.Net.Maui](url)  video: [https://www.youtube.com/watch?v=ostgj2xB_ok](url)  It is available in nuget package where the problem will be fixed .
If you need a temporary solution, then in CameraBarcodeReaderViewHandler.cs:

**Change this:**

`protected Readers.IBarcodeReader BarcodeReader => Services.GetService<Readers.IBarcodeReader>();`

**to:** 

`protected Readers.IBarcodeReader BarcodeReader
{
	get
	{
		var a = Services.GetService<Readers.IBarcodeReader>();
		if (a.Options?.Equals(this.Options) != true) a.Options = this.Options;
		return a;
	}
}
protected BarcodeReaderOptions Options { get; set; }`

**and this:**

`public static void MapOptions(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView cameraBarcodeReaderView) => handler.BarcodeReader.Options = cameraBarcodeReaderView.Options;`

**to:**

`public static void MapOptions(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView cameraBarcodeReaderView)
		{
            handler.Options = cameraBarcodeReaderView.Options;
        }`

**Comment by kajzik** [comment]
Don't use this project instead use [https://github.com/redth/ZXing.Net.Maui](https://github.com/redth/ZXing.Net.Maui)  video: [https://www.youtube.com/watch?v=ostgj2xB_ok](https://www.youtube.com/watch?v=ostgj2xB_ok)  It is available in nuget package where the problem will be fixed .
If you need a temporary solution, then in CameraBarcodeReaderViewHandler.cs:

**Change this:**

`protected Readers.IBarcodeReader BarcodeReader => Services.GetService<Readers.IBarcodeReader>();`

**to:** 

`protected Readers.IBarcodeReader BarcodeReader
{
	get
	{
		var a = Services.GetService<Readers.IBarcodeReader>();
		if (a.Options?.Equals(this.Options) != true) a.Options = this.Options;
		return a;
	}
}
protected BarcodeReaderOptions Options { get; set; }`

**and this:**

`public static void MapOptions(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView cameraBarcodeReaderView) => handler.BarcodeReader.Options = cameraBarcodeReaderView.Options;`

**to:**

`public static void MapOptions(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView cameraBarcodeReaderView)
		{
            handler.Options = cameraBarcodeReaderView.Options;
        }`

**Comment by julienGrd** [comment]
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work
