### ISSUE TITLE
Black view when using NavigationPage

### ISSUE THREAD

**Issue by rotronic-inr** [julienGrd/BigIslandBarcoding#7]
The CameraBarcodeReaderView can only be used in a MainPage that's set manually. When using navigation to push and pop pages, the CameraBarcodeReaderView is black.

Leads to black view in App.xaml.cs:
```
MainPage = new NavigationPage(new MainPage());
```

**Comment by julienGrd** [comment]
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work
