### ISSUE TITLE
No package for net6.0-windows installed

### ISSUE THREAD

**Issue by FrankPohl** [julienGrd/BigIslandBarcoding#8]
Hi,
I have installed the nuget package version 1.0.5 in my MAUI solution but the package was not installed for net6.0-windows10.0.19041.0.
For all other platforms the package is there.
Did I make a mistake or is windows not supported?

**Comment by BryanLow13082018** [comment]
There was never support for windows at the moment

**Comment by FrankPohl** [comment]
Will it be supported in a future relase?

**Comment by julienGrd** [comment]
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work
