### ISSUE TITLE
Failed to resolve assembly in .Net MAUI

### ISSUE THREAD

**Issue by BryanLow13082018** [julienGrd/BigIslandBarcoding#9]
![image](https://user-images.githubusercontent.com/42332748/172371431-3c9657d9-ee1a-4772-8951-83be05025e1f.png)

I have already added this to the xaml file, but on compilation, this error is thrown:

![image](https://user-images.githubusercontent.com/42332748/172371485-852a80fb-ea27-4b43-a369-4088ccd083a6.png)

These are my packages:
![image](https://user-images.githubusercontent.com/42332748/172371526-53eaae48-7656-4e67-aa36-f8eed06d16b1.png)

**Comment by BryanLow13082018** [comment]
I found out that if I download the project and copy the zxing.net.maui project to my project,  instead of using the library from nuget, I don't have this issue. Very weird.... hmm....

**Comment by umutazazi** [comment]
> I found out that if I download the project and copy the zxing.net.maui project to my project, instead of using the library from nuget, I don't have this issue. Very weird.... hmm....

Can you help me too ? How did you copy the project

**Comment by julienGrd** [comment]
this project (and associated package) have no reason to live anymore, since the original project ZXing.Net.Maui (https://github.com/Redth/ZXing.Net.Maui) was corrected and a package published. 

Please open issue in the original repository if something still not work
